title:              Note Space
email:              taejoon.park@gatech.edu
description:        TJ's Note Space
author:             Taejoon Park
baseurl:            ""
url:                "https://tpark71.github.io"

# Social Profiles
twitter_username:   
github_username:    tpark71
facebook_username:  
instagram_username:  
linkedin_username:  taejoon-park

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
highlighter: rouge
# kramdown:
#     syntax_highlighter_opts:
#         block:
#             line_numbers: true

permalink:          /:categories/:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
